version: '3.8'

services:
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile-frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/front
  back:
    build:
      context: ./backend
      dockerfile: Dockerfile-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/back